// Every lucide icon the admin uses, in one place, so icon choices are a single
// import away from being changed and the tree-shaken set stays visible.
//
// Note: lucide dropped its brand icons, so Instagram is represented by `Camera`.
export {
  AlertTriangle,
  ArrowUpDown,
  Award,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleUser,
  ClipboardList,
  Command,
  Download,
  ExternalLink,
  FileText,
  Footprints,
  GitMerge,
  GraduationCap,
  GripVertical,
  Image as ImageIcon,
  Inbox,
  Info,
  LayoutDashboard,
  Link as LinkIcon,
  Loader2,
  LogOut,
  Menu,
  MessageCircle,
  MessagesSquare,
  Moon,
  MountainSnow,
  Pencil,
  Plus,
  Presentation,
  Rss,
  Search,
  Share2,
  Sparkles,
  Sun,
  Tags,
  Trash2,
  Upload,
  Wrench,
  X,
} from "lucide-react";
