// audioManager — hand-rolled WebAudio, no Howler (§4.9). Module singleton,
// dynamically imported by AtlasFrame the first time the sound toggle turns
// ON — that click is the autoplay-unlock gesture, and zero audio bytes load
// for visitors who never enable sound.
//
// API: enable() / disable() / setBiome(key) / sfx(name).
//
// Loops (public/audio/loop-<key>.m4a) are generated by
// scripts/generate-atlas-audio.mjs with a 0.2 s guard pad on both sides of a
// seamless body — looping between GUARD and duration-GUARD lands on
// identical samples, immune to AAC edge padding. Region switches crossfade
// over 1 s with equal-power curves; buffers are fetched + decoded only when
// sound is on and the region is entered, then cached. visibilitychange
// suspends the context.

import SFX_MAP from "./sfxMap";
import { registerSfx } from "./sfxBus";

const GUARD = 0.2;
const XFADE = 1.0;
const BED_LEVEL = 0.9;

let ctx = null;
let master = null;
let enabled = false;
let biomeKey = null; // requested biome — remembered even while disabled
let current = null; // { key, source, gain }
const bufferCache = new Map(); // url -> Promise<AudioBuffer>
let sfxBuffer = null;

const equalPowerCurve = (from) => {
  const steps = 32;
  const curve = new Float32Array(steps);
  for (let i = 0; i < steps; i += 1) {
    const mix = i / (steps - 1);
    curve[i] = Math.sin(((from === 0 ? mix : 1 - mix) * Math.PI) / 2) ** 1;
  }
  return curve;
};
const FADE_IN = equalPowerCurve(0);
const FADE_OUT = equalPowerCurve(1);

const loadBuffer = (url) => {
  if (!bufferCache.has(url)) {
    const promise = fetch(url)
      .then((res) => {
        if (!res.ok) throw new Error(`audio fetch failed: ${url}`);
        return res.arrayBuffer();
      })
      .then((bytes) => ctx.decodeAudioData(bytes))
      .catch((err) => {
        bufferCache.delete(url); // allow a retry on the next enable/visit
        throw err;
      });
    bufferCache.set(url, promise);
  }
  return bufferCache.get(url);
};

const fadeOutCurrent = () => {
  if (!current) return;
  const { source, gain } = current;
  current = null;
  try {
    gain.gain.setValueCurveAtTime(FADE_OUT, ctx.currentTime, XFADE);
    source.stop(ctx.currentTime + XFADE + 0.05);
  } catch (e) {
    try { source.stop(); } catch (e2) { /* already stopped */ }
  }
};

const startLoop = async (key) => {
  const buffer = await loadBuffer(`/audio/loop-${key}.m4a`);
  // The world may have moved on while we fetched/decoded.
  if (!enabled || biomeKey !== key || (current && current.key === key)) return;
  fadeOutCurrent();
  const source = ctx.createBufferSource();
  source.buffer = buffer;
  source.loop = true;
  source.loopStart = GUARD;
  source.loopEnd = buffer.duration - GUARD;
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0, ctx.currentTime);
  gain.gain.setValueCurveAtTime(FADE_IN, ctx.currentTime, XFADE);
  source.connect(gain).connect(master);
  source.start(0, GUARD);
  current = { key, source, gain };
};

const onVisibility = () => {
  if (!ctx) return;
  if (document.hidden) {
    ctx.suspend();
  } else if (enabled) {
    ctx.resume();
  }
};

export const setBiome = (key) => {
  biomeKey = key || null;
  if (!enabled || !ctx) return;
  if (current && current.key === biomeKey) return;
  if (!biomeKey) {
    fadeOutCurrent();
    return;
  }
  startLoop(biomeKey).catch(() => { /* missing/undecodable asset: stay silent */ });
};

export const sfx = (name) => {
  if (!enabled || !ctx || !sfxBuffer) return;
  const spec = SFX_MAP[name];
  if (!spec) return;
  const source = ctx.createBufferSource();
  source.buffer = sfxBuffer;
  const gain = ctx.createGain();
  gain.gain.value = 0.8;
  source.connect(gain).connect(master);
  source.start(0, spec[0], spec[1]);
};

// Autoplay-policy escape hatch: when sound was already ON at page load,
// enable() runs without a user gesture and the context stays "suspended" —
// the next pointer/key gesture resumes it (sources started meanwhile are
// queued by the context and come in on resume).
const unlockOnGesture = () => {
  const unlock = () => {
    if (ctx && enabled) ctx.resume();
    document.removeEventListener("pointerdown", unlock, true);
    document.removeEventListener("keydown", unlock, true);
  };
  document.addEventListener("pointerdown", unlock, true);
  document.addEventListener("keydown", unlock, true);
};

export const enable = () => {
  if (!ctx) {
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return;
    ctx = new Ctx();
    master = ctx.createGain();
    master.gain.value = BED_LEVEL;
    master.connect(ctx.destination);
    document.addEventListener("visibilitychange", onVisibility);
    registerSfx(sfx);
  }
  enabled = true;
  ctx.resume().catch(() => { /* resumes on the unlock gesture instead */ });
  if (ctx.state === "suspended") unlockOnGesture();
  if (biomeKey) setBiome(biomeKey);
  // Pre-decode the SFX sprite (30 KB) so the first stamp lands on time.
  loadBuffer("/audio/sfx.m4a")
    .then((buffer) => { sfxBuffer = buffer; })
    .catch(() => { /* SFX stay silent if the sprite is missing */ });
};

export const disable = () => {
  enabled = false;
  if (!ctx) return;
  fadeOutCurrent();
  // Give the fade-out a beat, then park the context (no CPU while off).
  setTimeout(() => { if (!enabled && ctx) ctx.suspend(); }, (XFADE + 0.1) * 1000);
};
