// GENERATED by scripts/generate-guide-audio.mjs (npm run atlas:voice).
// [offset, duration] seconds into public/audio/guide-voice.m4a, one entry
// per beat id in src/atlas/guide/guideBeats.js. Do not edit by hand —
// re-run the script after changing a line the guide says.

const GUIDE_VOICE_MAP = {
  welcome: [0.00, 9.70],
  "first-stamp": [9.95, 6.82],
  "sound-hint": [17.01, 8.78],
  "egg-hint": [26.05, 6.50],
};

export default GUIDE_VOICE_MAP;
