// scripts/build-context.mjs
// Generates functions/lib/site-context.js from all site data files.
// Run automatically via: npm run prebuild / npm run prestart

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const dataDir = join(root, 'src', 'data');

// Ensure PUBLIC_URL is defined so sports/treks template literals don't produce "undefined/..."
process.env.PUBLIC_URL = process.env.PUBLIC_URL || '';

// Convert a filesystem path to a file:// URL string for dynamic import (required on Windows)
const imp = (p) => import(pathToFileURL(p).href);

// ── Load JS data files ────────────────────────────────────────────────────────
const books         = (await imp(join(dataDir, 'books.js'))).default;
const sports        = (await imp(join(dataDir, 'sports.js'))).default;
const treks         = (await imp(join(dataDir, 'treks.js'))).default;
const posts         = (await imp(join(dataDir, '100DaysToOffload.js'))).default;
const projects      = (await imp(join(dataDir, 'projects.js'))).default;
const contact       = (await imp(join(dataDir, 'contact.js'))).default;
const positions     = (await imp(join(dataDir, 'resume/positions.js'))).default;
const degrees       = (await imp(join(dataDir, 'resume/degrees.js'))).default;
const certifications = (await imp(join(dataDir, 'resume/certifications.js'))).default;
const { skills }    = await imp(join(dataDir, 'resume/skills.js'));

// ── Load markdown files ───────────────────────────────────────────────────────
const aboutRaw = await readFile(join(dataDir, 'about.md'), 'utf-8');
const nowRaw   = await readFile(join(dataDir, 'now.md'), 'utf-8');

// Extract intro block + the two most-recent ## sections from now.md
function extractRecentNow(raw) {
  const lines = raw.split('\n');
  const sectionStarts = [];
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].startsWith('## ')) sectionStarts.push(i);
  }
  // Keep up to the end of the 2nd section (or whole file if fewer sections)
  const cutoffLine = sectionStarts[2] !== undefined ? sectionStarts[2] : lines.length;
  return lines.slice(0, cutoffLine).join('\n').trim();
}

// ── Clean data (strip image/icon fields not useful for AI context) ────────────
const booksClean = books.map(({ id, title, author, category, language, year, tags, description }) =>
  ({ id, title, author, category, language, year, tags, description }));

const sportsClean = sports.map(({ id, title, date, place, distance, time, timeCertificateLink, bibNumber }) =>
  ({ id, title, date, place, distance, time, timeCertificateLink, bibNumber }));

const treksClean = treks.map(({ id, fort_name, trek_time, endurance_level, date, blog_link }) =>
  ({ id, fort_name, trek_time, endurance_level, date, ...(blog_link ? { blog_link } : {}) }));

const projectsClean = projects.map(({ title, subtitle, link, date, desc }) =>
  ({ title, subtitle, link, date, desc }));

const contactClean = contact.map(({ link, label }) => ({ link, label }));

const skillsClean = skills.map(({ title, competency, category }) =>
  ({ title, competency, category }));

// ── Build system prompt ───────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are a helpful AI assistant embedded on Sanket Tambare's personal portfolio website. Answer visitor questions about Sanket using the data provided below. Be friendly, concise, and conversational. If asked about something not covered by the data, say you don't have that information and suggest the visitor explore the relevant page on the site.

## About Sanket
${aboutRaw.trim()}

## What Sanket is doing now (recent updates)
${extractRecentNow(nowRaw)}

## Professional Experience
${JSON.stringify(positions, null, 2)}

## Education
${JSON.stringify(degrees, null, 2)}

## Certifications
${JSON.stringify(certifications, null, 2)}

## Skills
${JSON.stringify(skillsClean, null, 2)}

## Projects
${JSON.stringify(projectsClean, null, 2)}

## Books Read (${booksClean.length} books total)
${JSON.stringify(booksClean, null, 2)}

## Marathon & Race History (${sportsClean.length} races)
${JSON.stringify(sportsClean, null, 2)}

## Trek History (${treksClean.length} treks)
${JSON.stringify(treksClean, null, 2)}

## Blog Posts — 100 Days to Offload Challenge
${JSON.stringify(posts, null, 2)}

## Contact & Social Links
${JSON.stringify(contactClean, null, 2)}
`;

// ── Write output ──────────────────────────────────────────────────────────────
const outDir = join(root, 'functions', 'lib');
await mkdir(outDir, { recursive: true });

const output = `// AUTO-GENERATED by scripts/build-context.mjs — do not edit manually
// Re-run: node scripts/build-context.mjs
export const SYSTEM_PROMPT = ${JSON.stringify(SYSTEM_PROMPT)};
`;

await writeFile(join(outDir, 'site-context.js'), output, 'utf-8');
console.log('[build-context] Written functions/lib/site-context.js');
console.log(`[build-context] System prompt: ${SYSTEM_PROMPT.length.toLocaleString()} chars`);
