// Share-card URLs, and the image an entity route unfurls with.
//
// There is no renderer at request time. Cards are PNGs generated by
// `npm run og:fallbacks` and committed to `public/og/`, so an og:image is a
// plain static asset: nothing to time out, nothing to fall back from. An
// earlier build rendered them on demand at `/api/og/<kind>/<id>.png` and that
// is exactly what went wrong — Workers Free allows 10ms CPU per request and a
// satori + resvg pass costs ~400ms, so production returned 1102 and the tag
// resolved to nothing. See docs/og-cards.md.

// The committed card for a section. Every route's og:image is one of these,
// unless the route is an entity that carries its own photo.
export const ogStaticUrl = (slug, siteUrl = "") => `${siteUrl}/og/${slug}.png`;

// Which committed card each entity kind falls back to when the row has no
// photo of its own — which, for books, blogs, decks, tags and shares, is
// always. `src/data/routeManifest.test.js` asserts every slug here is a real
// committed PNG, so a new detail route cannot ship pointing at nothing.
export const CARD_FALLBACKS = {
  book: "books",
  blog: "100-days-to-offload",
  sport: "sports",
  trek: "treks",
  project: "projects",
  presentation: "presentations",
  microblog: "micro-blog",
  tag: "tags",
  "ask-share": "ask-share",
};

// True for our own cards, which are all exactly 1200x630. Both meta layers use
// this to decide whether to DECLARE og:image:width/height: an entity's own
// photo is whatever shape the camera was, and asserting 1200x630 over a 900px
// portrait makes every platform crop it wrong. Undeclared, they measure it.
export const isCardImage = (url) => /\/og\/[^/]+\.png$/.test(String(url || ""));

// Resolves a stored image path to a public URL. PostgREST rows hold RELATIVE
// paths for anything uploaded through /admin (see toStorageUrl in
// src/lib/supabaseClient.js, which does the same job on the client but cannot
// be reused here because it imports the supabase-js client). Absolute URLs pass
// through untouched, which is what makes this safe to call on a client row that
// `toStorageImages` has already absolutised — hence the `supabaseUrl` default.
export function storageUrl(value, supabaseUrl = "") {
  if (!value) return null;
  const path = String(value);
  if (/^https?:\/\//i.test(path)) return path;
  const clean = path.startsWith("/") ? path : `/${path}`;
  return `${supabaseUrl}/storage/v1/object/public/media${clean}`;
}

// First usable image out of a `slide_images` column, which holds either bare
// URL strings or `{ url }` objects depending on when the row was written.
export function firstSlideImage(slideImages, supabaseUrl = "") {
  if (!Array.isArray(slideImages)) return null;
  const found = slideImages.find((entry) => (typeof entry === "string" ? entry : entry && entry.url));
  if (!found) return null;
  return storageUrl(typeof found === "string" ? found : found.url, supabaseUrl);
}

export default ogStaticUrl;
